spring:
  application:
    name: psiu-api
  datasource:
#    username: root
#    password: root
    url: jdbc:mysql://vxdc4mc28whfqh3f:pnt6gtim05k13fy8@eyvqcfxf5reja3nv.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/w5f3jfjuvmw1urq1
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: 12345
    expiration: 1000000
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api