spring:
  application:
    name: psiu-api
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/psiuapi
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: 12345
    access:
      expiration: 1000000
    refresh:
      expiration: 10000000
  api-key: 12345
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api