spring:
  application:
    name: psiu-api
  datasource:
    username: 7jrmmzwtrkw0
    password: pscale_pw_wV-3T-Oi3xiSCIt6HDJ76ys-E4sfEjSjizo7w35gZ2w
    url: jdbc:mysql://352c7m0xxgy7.aws-sa-east-1-1.psdb.cloud/psiu-api-kt?sslMode=VERIFY_IDENTITY
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: 12345
    expiration: 1000000
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api