spring:
  application:
    name: psiu-api
  datasource:
#    username: root
#    password: root
    url: jdbc:mysql://nftdn0okrq5p6nwe:iesf1b1z85v85gsu@en1ehf30yom7txe7.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/gid8w9omkb77d39p
  jpa:
    hibernate:
      ddl-auto: update
app:
  jwt:
    secret: 12345
    expiration: 1000000
springdoc:
  api-docs:
    path: /api-docs
server:
  servlet:
    context-path: /api